export const FLASHCARDS = [
  {
    id: 1,
    country: "Afghanistan",
    city: "Kabul",
    continent: "Asia",
  },
  {
    id: 2,
    country: "Albania",
    city: "Tirana",
    continent: "Europe",
  },
  {
    id: 3,
    country: "Algeria",
    city: "Alger",
    continent: "Africa",
  },
  {
    id: 4,
    country: "American Samoa",
    city: "Fagatogo",
    continent: "Oceania",
  },
  {
    id: 5,
    country: "Andorra",
    city: "Andorra la Vella",
    continent: "Europe",
  },
  {
    id: 6,
    country: "Angola",
    city: "Luanda",
    continent: "Africa",
  },
  {
    id: 7,
    country: "Anguilla",
    city: "The Valley",
    continent: "North America",
  },
  {
    id: 8,
    country: "Antarctica",
    city: "-",
    continent: "Antarctica",
  },
  {
    id: 9,
    country: "Antigua and Barbuda",
    city: "Saint John's",
    continent: "North America",
  },
  {
    id: 10,
    country: "Argentina",
    city: "Buenos Aires",
    continent: "South America",
  },
  {
    id: 11,
    country: "Armenia",
    city: "Yerevan",
    continent: "Asia",
  },
  {
    id: 12,
    country: "Aruba",
    city: "Oranjestad",
    continent: "North America",
  },
  {
    id: 13,
    country: "Australia",
    city: "Canberra",
    continent: "Oceania",
  },
  {
    id: 14,
    country: "Austria",
    city: "Wien",
    continent: "Europe",
  },
  {
    id: 15,
    country: "Azerbaijan",
    city: "Baku",
    continent: "Asia",
  },
  {
    id: 16,
    country: "Bahamas",
    city: "Nassau",
    continent: "North America",
  },
  {
    id: 17,
    country: "Bahrain",
    city: "al" - "Manama",
    continent: "Asia",
  },
  {
    id: 18,
    country: "Bangladesh",
    city: "Dhaka",
    continent: "Asia",
  },
  {
    id: 19,
    country: "Barbados",
    city: "Bridgetown",
    continent: "North America",
  },
  {
    id: 20,
    country: "Belarus",
    city: "Minsk",
    continent: "Europe",
  },
  {
    id: 21,
    country: "Belgium",
    city: "Bruxelles [Brussel]",
    continent: "Europe",
  },
  {
    id: 22,
    country: "Belize",
    city: "Belmopan",
    continent: "North America",
  },
  {
    id: 23,
    country: "Benin",
    city: "Porto" - "Novo",
    continent: "Africa",
  },
  {
    id: 24,
    country: "Bermuda",
    city: "Hamilton",
    continent: "North America",
  },
  {
    id: 25,
    country: "Bhutan",
    city: "Thimphu",
    continent: "Asia",
  },
  {
    id: 26,
    country: "Bolivia",
    city: "La Paz",
    continent: "South America",
  },
  {
    id: 27,
    country: "Bosnia and Herzegovina",
    city: "Sarajevo",
    continent: "Europe",
  },
  {
    id: 28,
    country: "Botswana",
    city: "Gaborone",
    continent: "Africa",
  },
  {
    id: 29,
    country: "Bouvet Island",
    city: "-",
    continent: "Antarctica",
  },
  {
    id: 30,
    country: "Brazil",
    city: "Brasília",
    continent: "South America",
  },
  {
    id: 31,
    country: "British Indian Ocean Territory",
    city: "-",
    continent: "Asia",
  },
  {
    id: 32,
    country: "Brunei",
    city: "Bandar Seri Begawan",
    continent: "Asia",
  },
  {
    id: 33,
    country: "Bulgaria",
    city: "Sofia",
    continent: "Europe",
  },
  {
    id: 34,
    country: "Burkina Faso",
    city: "Ouagadougou",
    continent: "Africa",
  },
  {
    id: 35,
    country: "Burundi",
    city: "Bujumbura",
    continent: "Africa",
  },
  {
    id: 36,
    country: "Cambodia",
    city: "Phnom Penh",
    continent: "Asia",
  },
  {
    id: 37,
    country: "Cameroon",
    city: "Yaounde",
    continent: "Africa",
  },
  {
    id: 38,
    country: "Canada",
    city: "Ottawa",
    continent: "North America",
  },
  {
    id: 39,
    country: "Cape Verde",
    city: "Praia",
    continent: "Africa",
  },
  {
    id: 40,
    country: "Cayman Islands",
    city: "George Town",
    continent: "North America",
  },
  {
    id: 41,
    country: "Central African Republic",
    city: "Bangui",
    continent: "Africa",
  },
  {
    id: 42,
    country: "Chad",
    city: "N'Djamena",
    continent: "Africa",
  },
  {
    id: 43,
    country: "Chile",
    city: "Santiago de Chile",
    continent: "South America",
  },
  {
    id: 44,
    country: "China",
    city: "Peking",
    continent: "Asia",
  },
  {
    id: 45,
    country: "Christmas Island",
    city: "Flying Fish Cove",
    continent: "Asia",
  },
  {
    id: 46,
    country: "Cocos (Keeling) Islands",
    city: "West Island",
    continent: "Asia",
  },
  {
    id: 47,
    country: "Colombia",
    city: "Santaf",
    continent: "South America",
  },
  {
    id: 48,
    country: "Comoros",
    city: "Moroni",
    continent: "Africa",
  },
  {
    id: 49,
    country: "Congo",
    city: "Brazzaville",
    continent: "Africa",
  },
  {
    id: 50,
    country: "Cook Islands",
    city: "Avarua",
    continent: "Oceania",
  },
  {
    id: 51,
    country: "Costa Rica",
    city: "San José",
    continent: "North America",
  },
  {
    id: 52,
    country: "Croatia",
    city: "Zagreb",
    continent: "Europe",
  },
  {
    id: 53,
    country: "Cuba",
    city: "La Habana",
    continent: "North America",
  },
  {
    id: 54,
    country: "Cyprus",
    city: "Nicosia",
    continent: "Asia",
  },
  {
    id: 55,
    country: "Czech Republic",
    city: "Praha",
    continent: "Europe",
  },
  {
    id: 56,
    country: "Denmark",
    city: "Copenhagen",
    continent: "Europe",
  },
  {
    id: 57,
    country: "Djibouti",
    city: "Djibouti",
    continent: "Africa",
  },
  {
    id: 58,
    country: "Dominica",
    city: "Roseau",
    continent: "North America",
  },
  {
    id: 59,
    country: "Dominican Republic",
    city: "Santo Domingo de Guzm",
    continent: "North America",
  },
  {
    id: 60,
    country: "East Timor",
    city: "Dili",
    continent: "Asia",
  },
  {
    id: 61,
    country: "Ecuador",
    city: "Quito",
    continent: "South America",
  },
  {
    id: 62,
    country: "Egypt",
    city: "Cairo",
    continent: "Africa",
  },
  {
    id: 63,
    country: "El Salvador",
    city: "San Salvador",
    continent: "North America",
  },
  {
    id: 64,
    country: "England",
    city: "London",
    continent: "Europe",
  },
  {
    id: 65,
    country: "Equatorial Guinea",
    city: "Malabo",
    continent: "Africa",
  },
  {
    id: 66,
    country: "Eritrea",
    city: "Asmara",
    continent: "Africa",
  },
  {
    id: 67,
    country: "Estonia",
    city: "Tallinn",
    continent: "Europe",
  },
  {
    id: 68,
    country: "Ethiopia",
    city: "Addis Abeba",
    continent: "Africa",
  },
  {
    id: 69,
    country: "Falkland Islands",
    city: "Stanley",
    continent: "South America",
  },
  {
    id: 70,
    country: "Faroe Islands",
    city: "Tórshavn",
    continent: "Europe",
  },
  {
    id: 71,
    country: "Fiji Islands",
    city: "Suva",
    continent: "Oceania",
  },
  {
    id: 72,
    country: "Finland",
    city: "Helsinki [Helsingfors]",
    continent: "Europe",
  },
  {
    id: 73,
    country: "France",
    city: "Paris",
    continent: "Europe",
  },
  {
    id: 74,
    country: "French Guiana",
    city: "Cayenne",
    continent: "South America",
  },
  {
    id: 75,
    country: "French Polynesia",
    city: "Papeete",
    continent: "Oceania",
  },
  {
    id: 76,
    country: "French Southern territories",
    city: "-",
    continent: "Africa",
  },
  {
    id: 77,
    country: "Gabon",
    city: "Libreville",
    continent: "Africa",
  },
  {
    id: 78,
    country: "Gambia",
    city: "Banjul",
    continent: "Africa",
  },
  {
    id: 79,
    country: "Georgia",
    city: "Tbilisi",
    continent: "Asia",
  },
  {
    id: 80,
    country: "Germany",
    city: "Berlin",
    continent: "Europe",
  },
  {
    id: 81,
    country: "Ghana",
    city: "Accra",
    continent: "Africa",
  },
  {
    id: 82,
    country: "Gibraltar",
    city: "Gibraltar",
    continent: "Europe",
  },
  {
    id: 83,
    country: "Greece",
    city: "Athenai",
    continent: "Europe",
  },
  {
    id: 84,
    country: "Greenland",
    city: "Nuuk",
    continent: "North America",
  },
  {
    id: 85,
    country: "Grenada",
    city: "Saint George's",
    continent: "North America",
  },
  {
    id: 86,
    country: "Guadeloupe",
    city: "Basse" - "Terre",
    continent: "North America",
  },
  {
    id: 87,
    country: "Guam",
    city: "Aga",
    continent: "Oceania",
  },
  {
    id: 88,
    country: "Guatemala",
    city: "Ciudad de Guatemala",
    continent: "North America",
  },
  {
    id: 89,
    country: "Guinea",
    city: "Conakry",
    continent: "Africa",
  },
  {
    id: 90,
    country: "Guinea" - "Bissau",
    city: "Bissau",
    continent: "Africa",
  },
  {
    id: 91,
    country: "Guyana",
    city: "Georgetown",
    continent: "South America",
  },
  {
    id: 92,
    country: "Haiti",
    city: "Port" - "au" - "Prince",
    continent: "North America",
  },
  {
    id: 93,
    country: "Heard Island and McDonald Islands",
    city: "-",
    continent: "Antarctica",
  },
  {
    id: 94,
    country: "Holy See (Vatican City State)",
    city: "Citt",
    continent: "Europe",
  },
  {
    id: 95,
    country: "Honduras",
    city: "Tegucigalpa",
    continent: "North America",
  },
  {
    id: 96,
    country: "Hong Kong",
    city: "Victoria",
    continent: "Asia",
  },
  {
    id: 97,
    country: "Hungary",
    city: "Budapest",
    continent: "Europe",
  },
  {
    id: 98,
    country: "Iceland",
    city: "Reykjavík",
    continent: "Europe",
  },
  {
    id: 99,
    country: "India",
    city: "New Delhi",
    continent: "Asia",
  },
  {
    id: 100,
    country: "Indonesia",
    city: "Jakarta",
    continent: "Asia",
  },
  {
    id: 101,
    country: "Iran",
    city: "Tehran",
    continent: "Asia",
  },
  {
    id: 102,
    country: "Iraq",
    city: "Baghdad",
    continent: "Asia",
  },
  {
    id: 103,
    country: "Ireland",
    city: "Dublin",
    continent: "Europe",
  },
  {
    id: 104,
    country: "Israel",
    city: "Jerusalem",
    continent: "Asia",
  },
  {
    id: 105,
    country: "Italy",
    city: "Roma",
    continent: "Europe",
  },
  {
    id: 106,
    country: "Ivory Coast",
    city: "Yamoussoukro",
    continent: "Africa",
  },
  {
    id: 107,
    country: "Jamaica",
    city: "Kingston",
    continent: "North America",
  },
  {
    id: 108,
    country: "Japan",
    city: "Tokyo",
    continent: "Asia",
  },
  {
    id: 109,
    country: "Jordan",
    city: "Amman",
    continent: "Asia",
  },
  {
    id: 110,
    country: "Kazakhstan",
    city: "Astana",
    continent: "Asia",
  },
  {
    id: 111,
    country: "Kenya",
    city: "Nairobi",
    continent: "Africa",
  },
  {
    id: 112,
    country: "Kiribati",
    city: "Bairiki",
    continent: "Oceania",
  },
  {
    id: 113,
    country: "Kuwait",
    city: "Kuwait",
    continent: "Asia",
  },
  {
    id: 114,
    country: "Kyrgyzstan",
    city: "Bishkek",
    continent: "Asia",
  },
  {
    id: 115,
    country: "Laos",
    city: "Vientiane",
    continent: "Asia",
  },
  {
    id: 116,
    country: "Latvia",
    city: "Riga",
    continent: "Europe",
  },
  {
    id: 117,
    country: "Lebanon",
    city: "Beirut",
    continent: "Asia",
  },
  {
    id: 118,
    country: "Lesotho",
    city: "Maseru",
    continent: "Africa",
  },
  {
    id: 119,
    country: "Liberia",
    city: "Monrovia",
    continent: "Africa",
  },
  {
    id: 120,
    country: "Libyan Arab Jamahiriya",
    city: "Tripoli",
    continent: "Africa",
  },
  {
    id: 121,
    country: "Liechtenstein",
    city: "Vaduz",
    continent: "Europe",
  },
  {
    id: 122,
    country: "Lithuania",
    city: "Vilnius",
    continent: "Europe",
  },
  {
    id: 123,
    country: "Luxembourg",
    city: "Luxembourg [Luxemburg/Luxembourg/Ville de Luxembourg]",
    continent: "Europe",
  },
  {
    id: 124,
    country: "Macao",
    city: "Macao",
    continent: "Asia",
  },
  {
    id: 125,
    country: "North Macedonia",
    city: "Skopje",
    continent: "Europe",
  },
  {
    id: 126,
    country: "Madagascar",
    city: "Antananarivo",
    continent: "Africa",
  },
  {
    id: 127,
    country: "Malawi",
    city: "Lilongwe",
    continent: "Africa",
  },
  {
    id: 128,
    country: "Malaysia",
    city: "Kuala Lumpur",
    continent: "Asia",
  },
  {
    id: 129,
    country: "Maldives",
    city: "Male",
    continent: "Asia",
  },
  {
    id: 130,
    country: "Mali",
    city: "Bamako",
    continent: "Africa",
  },
  {
    id: 131,
    country: "Malta",
    city: "Valletta",
    continent: "Europe",
  },
  {
    id: 132,
    country: "Marshall Islands",
    city: "Dalap" - "Uliga" - "Darrit",
    continent: "Oceania",
  },
  {
    id: 133,
    country: "Martinique",
    city: "Fort" - "de" - "France",
    continent: "North America",
  },
  {
    id: 134,
    country: "Mauritania",
    city: "Nouakchott",
    continent: "Africa",
  },
  {
    id: 135,
    country: "Mauritius",
    city: "Port" - "Louis",
    continent: "Africa",
  },
  {
    id: 136,
    country: "Mayotte",
    city: "Mamoutzou",
    continent: "Africa",
  },
  {
    id: 137,
    country: "Mexico",
    city: "Ciudad de M",
    continent: "North America",
  },
  {
    id: 138,
    country: "Micronesia, Federated States of",
    city: "Palikir",
    continent: "Oceania",
  },
  {
    id: 139,
    country: "Moldova",
    city: "Chisinau",
    continent: "Europe",
  },
  {
    id: 140,
    country: "Monaco",
    city: "Monaco" - "Ville",
    continent: "Europe",
  },
  {
    id: 141,
    country: "Mongolia",
    city: "Ulan Bator",
    continent: "Asia",
  },
  {
    id: 142,
    country: "Montenegro",
    city: "Podgorica",
    continent: "Europe",
  },
  {
    id: 143,
    country: "Montserrat",
    city: "Plymouth",
    continent: "North America",
  },
  {
    id: 144,
    country: "Morocco",
    city: "Rabat",
    continent: "Africa",
  },
  {
    id: 145,
    country: "Mozambique",
    city: "Maputo",
    continent: "Africa",
  },
  {
    id: 146,
    country: "Myanmar",
    city: "Rangoon (Yangon)",
    continent: "Asia",
  },
  {
    id: 147,
    country: "Namibia",
    city: "Windhoek",
    continent: "Africa",
  },
  {
    id: 148,
    country: "Nauru",
    city: "Yaren",
    continent: "Oceania",
  },
  {
    id: 149,
    country: "Nepal",
    city: "Kathmandu",
    continent: "Asia",
  },
  {
    id: 150,
    country: "Netherlands",
    city: "Amsterdam",
    continent: "Europe",
  },
  {
    id: 151,
    country: "Netherlands Antilles",
    city: "Willemstad",
    continent: "North America",
  },
  {
    id: 152,
    country: "New Caledonia",
    city: "Nouméa",
    continent: "Oceania",
  },
  {
    id: 153,
    country: "New Zealand",
    city: "Wellington",
    continent: "Oceania",
  },
  {
    id: 154,
    country: "Nicaragua",
    city: "Managua",
    continent: "North America",
  },
  {
    id: 155,
    country: "Niger",
    city: "Niamey",
    continent: "Africa",
  },
  {
    id: 156,
    country: "Nigeria",
    city: "Abuja",
    continent: "Africa",
  },
  {
    id: 157,
    country: "Niue",
    city: "Alofi",
    continent: "Oceania",
  },
  {
    id: 158,
    country: "Norfolk Island",
    city: "Kingston",
    continent: "Oceania",
  },
  {
    id: 159,
    country: "North Korea",
    city: "Pyongyang",
    continent: "Asia",
  },
  {
    id: 160,
    country: "Northern Ireland",
    city: "Belfast",
    continent: "Europe",
  },
  {
    id: 161,
    country: "Northern Mariana Islands",
    city: "Garapan",
    continent: "Oceania",
  },
  {
    id: 162,
    country: "Norway",
    city: "Oslo",
    continent: "Europe",
  },
  {
    id: 163,
    country: "Oman",
    city: "Masqat",
    continent: "Asia",
  },
  {
    id: 164,
    country: "Pakistan",
    city: "Islamabad",
    continent: "Asia",
  },
  {
    id: 165,
    country: "Palau",
    city: "Koror",
    continent: "Oceania",
  },
  {
    id: 166,
    country: "Palestine",
    city: "Gaza",
    continent: "Asia",
  },
  {
    id: 167,
    country: "Panama",
    city: "Ciudad de Panamá",
    continent: "North America",
  },
  {
    id: 168,
    country: "Papua New Guinea",
    city: "Port Moresby",
    continent: "Oceania",
  },
  {
    id: 169,
    country: "Paraguay",
    city: "Asunción",
    continent: "South America",
  },
  {
    id: 170,
    country: "Peru",
    city: "Lima",
    continent: "South America",
  },
  {
    id: 171,
    country: "Philippines",
    city: "Manila",
    continent: "Asia",
  },
  {
    id: 172,
    country: "Pitcairn",
    city: "Adamstown",
    continent: "Oceania",
  },
  {
    id: 173,
    country: "Poland",
    city: "Warszawa",
    continent: "Europe",
  },
  {
    id: 174,
    country: "Portugal",
    city: "Lisboa",
    continent: "Europe",
  },
  {
    id: 175,
    country: "Puerto Rico",
    city: "San Juan",
    continent: "North America",
  },
  {
    id: 176,
    country: "Qatar",
    city: "Doha",
    continent: "Asia",
  },
  {
    id: 177,
    country: "Reunion",
    city: "Saint" - "Denis",
    continent: "Africa",
  },
  {
    id: 178,
    country: "Romania",
    city: "Bucuresti",
    continent: "Europe",
  },
  {
    id: 179,
    country: "Russian Federation",
    city: "Moscow",
    continent: "Europe/Asia",
  },
  {
    id: 180,
    country: "Rwanda",
    city: "Kigali",
    continent: "Africa",
  },
  {
    id: 181,
    country: "Saint Helena",
    city: "Jamestown",
    continent: "Africa",
  },
  {
    id: 182,
    country: "Saint Kitts and Nevis",
    city: "Basseterre",
    continent: "North America",
  },
  {
    id: 183,
    country: "Saint Lucia",
    city: "Castries",
    continent: "North America",
  },
  {
    id: 184,
    country: "Saint Pierre and Miquelon",
    city: "Saint" - "Pierre",
    continent: "North America",
  },
  {
    id: 185,
    country: "Saint Vincent and the Grenadines",
    city: "Kingstown",
    continent: "North America",
  },
  {
    id: 186,
    country: "Samoa",
    city: "Apia",
    continent: "Oceania",
  },
  {
    id: 187,
    country: "San Marino",
    city: "San Marino",
    continent: "Europe",
  },
  {
    id: 188,
    country: "Sao Tome and Principe",
    city: "São Tomé",
    continent: "Africa",
  },
  {
    id: 189,
    country: "Saudi Arabia",
    city: "Riyadh",
    continent: "Asia",
  },
  {
    id: 190,
    country: "Scotland",
    city: "Edinburgh",
    continent: "Europe",
  },
  {
    id: 191,
    country: "Senegal",
    city: "Dakar",
    continent: "Africa",
  },
  {
    id: 192,
    country: "Serbia",
    city: "Belgrade",
    continent: "Europe",
  },
  {
    id: 193,
    country: "Seychelles",
    city: "Victoria",
    continent: "Africa",
  },
  {
    id: 194,
    country: "Sierra Leone",
    city: "Freetown",
    continent: "Africa",
  },
  {
    id: 195,
    country: "Singapore",
    city: "Singapore",
    continent: "Asia",
  },
  {
    id: 196,
    country: "Slovakia",
    city: "Bratislava",
    continent: "Europe",
  },
  {
    id: 197,
    country: "Slovenia",
    city: "Ljubljana",
    continent: "Europe",
  },
  {
    id: 198,
    country: "Solomon Islands",
    city: "Honiara",
    continent: "Oceania",
  },
  {
    id: 199,
    country: "Somalia",
    city: "Mogadishu",
    continent: "Africa",
  },
  {
    id: 200,
    country: "South Africa",
    city: "Pretoria",
    continent: "Africa",
  },
  {
    id: 201,
    country: "South Georgia and the South Sandwich Islands",
    city: "-",
    continent: "Antarctica",
  },
  {
    id: 202,
    country: "South Korea",
    city: "Seoul",
    continent: "Asia",
  },
  {
    id: 203,
    country: "South Sudan",
    city: "Juba",
    continent: "Africa",
  },
  {
    id: 204,
    country: "Spain",
    city: "Madrid",
    continent: "Europe",
  },
  {
    id: 205,
    country: "Sri Lanka",
    city: "Colombo, Sri Jayawardenepura Kotte",
    continent: "Asia",
  },
  {
    id: 206,
    country: "Sudan",
    city: "Khartoum",
    continent: "Africa",
  },
  {
    id: 207,
    country: "Suriname",
    city: "Paramaribo",
    continent: "South America",
  },
  {
    id: 208,
    country: "Svalbard and Jan Mayen",
    city: "Longyearbyen",
    continent: "Europe",
  },
  {
    id: 209,
    country: "Eswatini",
    city: "Mbabane",
    continent: "Africa",
  },
  {
    id: 210,
    country: "Sweden",
    city: "Stockholm",
    continent: "Europe",
  },
  {
    id: 211,
    country: "Switzerland",
    city: "Bern",
    continent: "Europe",
  },
  {
    id: 212,
    country: "Syria",
    city: "Damascus",
    continent: "Asia",
  },
  {
    id: 213,
    country: "Tajikistan",
    city: "Dushanbe",
    continent: "Asia",
  },
  {
    id: 214,
    country: "Tanzania",
    city: "Dodoma",
    continent: "Africa",
  },
  {
    id: 215,
    country: "Thailand",
    city: "Bangkok",
    continent: "Asia",
  },
  {
    id: 216,
    country: "The Democratic Republic of Congo",
    city: "Kinshasa",
    continent: "Africa",
  },
  {
    id: 217,
    country: "Togo",
    city: "Lomé",
    continent: "Africa",
  },
  {
    id: 218,
    country: "Tokelau",
    city: "Fakaofo",
    continent: "Oceania",
  },
  {
    id: 219,
    country: "Tonga",
    city: "Nuku'alofa",
    continent: "Oceania",
  },
  {
    id: 220,
    country: "Trinidad and Tobago",
    city: "Port" - "of" - "Spain",
    continent: "North America",
  },
  {
    id: 221,
    country: "Tunisia",
    city: "Tunis",
    continent: "Africa",
  },
  {
    id: 222,
    country: "Turkey",
    city: "Ankara",
    continent: "Asia",
  },
  {
    id: 223,
    country: "Turkmenistan",
    city: "Ashgabat",
    continent: "Asia",
  },
  {
    id: 224,
    country: "Turks and Caicos Islands",
    city: "Cockburn Town",
    continent: "North America",
  },
  {
    id: 225,
    country: "Tuvalu",
    city: "Funafuti",
    continent: "Oceania",
  },
  {
    id: 226,
    country: "Uganda",
    city: "Kampala",
    continent: "Africa",
  },
  {
    id: 227,
    country: "Ukraine",
    city: "Kyiv",
    continent: "Europe",
  },
  {
    id: 228,
    country: "United Arab Emirates",
    city: "Abu Dhabi",
    continent: "Asia",
  },
  {
    id: 229,
    country: "United Kingdom",
    city: "London",
    continent: "Europe",
  },
  {
    id: 230,
    country: "United States",
    city: "Washington",
    continent: "North America",
  },
  {
    id: 231,
    country: "United States Minor Outlying Islands",
    city: "-",
    continent: "North America",
  },
  {
    id: 232,
    country: "Uruguay",
    city: "Montevideo",
    continent: "South America",
  },
  {
    id: 233,
    country: "Uzbekistan",
    city: "Toskent",
    continent: "Asia",
  },
  {
    id: 234,
    country: "Vanuatu",
    city: "Port" - "Vila",
    continent: "Oceania",
  },
  {
    id: 235,
    country: "Venezuela",
    city: "Caracas",
    continent: "South America",
  },
  {
    id: 236,
    country: "Vetican City",
    city: "Vetican City",
    continent: "Europe",
  },
  {
    id: 237,
    country: "Vietnam",
    city: "Hanoi",
    continent: "Asia",
  },
  {
    id: 238,
    country: "Virgin Islands, British",
    city: "Road Town",
    continent: "North America",
  },
  {
    id: 239,
    country: "Virgin Islands, U.S.",
    city: "Charlotte Amalie",
    continent: "North America",
  },
  {
    id: 240,
    country: "Wales",
    city: "Cardiff",
    continent: "Europe",
  },
  {
    id: 241,
    country: "Wallis and Futuna",
    city: "Mata" - "Utu",
    continent: "Oceania",
  },
  {
    id: 242,
    country: "Western Sahara",
    city: "El" - "Aaiún",
    continent: "Africa",
  },
  {
    id: 243,
    country: "Yemen",
    city: "Sana'a",
    continent: "Asia",
  },
  {
    id: 244,
    country: "Zambia",
    city: "Lusaka",
    continent: "Africa",
  },
  {
    id: 245,
    country: "Zimbabwe",
    city: "Harare",
    continent: "Africa",
  },
];
